import {ChakraProvider,Container} from "@chakra-ui/react";
import Navbar from "../components/Navbar";
import "../styles/globals.css";
import Head from "next/head";
import {useRouter} from "next/router";
function MyApp({ Component, pageProps }) {
  return (
    <>
     <Head>
        <title>CRUD || {Component.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <ChakraProvider>
      <Navbar/>
      <Container 
      p="30px 20px"
      maxW="900px" 
      borderRight="1px solid"
      borderLeft="1px solid"
      borderBottom="1px solid"
      borderColor="gray.300"
      >
        <Component {...pageProps} />
      </Container>
    </ChakraProvider>
    </>
    )
}

export default MyApp
